services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    build: .
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./:/var/www/html

  frontend:
    build: ./frontend/skejul-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://localhost:${APP_PORT}"
    volumes:
      - ./frontend/skejul-frontend:/app

volumes:
  db_data:
